name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Flutter build and deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'

    - name: Setting for Web Deploy
      run: |
        flutter upgrade
        flutter config --enable-web

    - name: Install
      run: |
        flutter package pub get

    - name: Build
      run: flutter build web
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./build/web
